on:
  schedule:
    - cron: "0 0 23 * *" #runs every day at 11 PM

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - run: pip install -r requirements.txt
      - name: Execute py script
        run: |
          python3 harvest.py utrecht
      - name: Archive data
        uses: actions/upload-artifact@v3
        with:
          name: utrecht
          path: data/utrecht.json